/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WS3DApp;

public class App {
    private static MainFrameController controller;

    public static void main(String[] args) {
        controller = new MainFrameController();
    }
}
